# action.yml
name: hello-world
description: greeting
inputs:
  name:  # id of input
    description: name
    required: true
    default: ''
outputs:
  text: # id of output
    description: execute end time
runs: ubuntu-latest
run: echo hello world
