name: hello-world-docker

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |
        find .
    - name: Hello world action step
      id: hello
      uses: ./.github/actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
