# This is a basic workflow to help you get started with Actions

name: share data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  plus:
    name: plus 
    runs-on: ubuntu-latest
    steps:
      - run: |
          expr 1024 + 512 > plus-result.txt
      - name: Upload plus result
        uses: actions/upload-artifact@v1
        with:
          name: plus-result
          path: plus-result.txt  
      - run: |
          find . 
          cat ./plus-result.txt
  multiply:
    name: multiply
    needs: plus
    runs-on: windows-latest
    steps:
      - name: download plus result
        uses: actions/download-artifact@v1
        with:
          name: plus-result
      - shell: bash
        run: |
          value=`cat plus-result/plus-result.txt`
          expr $value \* 2 > plus-result/plus-result.txt
      - name: upload multiply result
        uses: actions/upload-artifact@v1
        with:
          name: plus-result
          path: plus-result/plus-result.txt  
      - shell: bash
        run: |
          find . 
          cat ./plus-result/plus-result.txt
