name: tmp action for testing

on:
  push:

jobs:
  hello-world:
    runs-on: self-hosted
    name: A job to say hello
    steps:
    # checkout
    - name: checkout
      uses: actions/checkout@v2
    # use local action
    - name: foo-action
      id: foo-action
      uses: ./.github/actions/foo-action
      with:
        name: foofoo
    # Use the output from the foo-action step
    - name: output
      run: echo "${{ steps.foo-action.outputs.text }}"
